# Generated by Django 4.0.2 on 2024-01-21 15:23

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('updatedAt', models.DateTimeField()),
                ('temperature', models.TextField()),
            ],
        ),
    ]
